### ISSUE TITLE
release a new gem?

### ISSUE THREAD

**Issue by jjb** [ericallam/font_assets#36]
I think this alone warrants a bugfix release: https://github.com/ericallam/font_assets/pull/33/files

**Comment by christiannelson** [comment]
:+1:

**Comment by christiannelson** [comment]
@ericallam Would you consider giving another developer what they need to make a point release?

**Comment by edlebert** [comment]
Woff2 is broken, which really limits the usefulness of this gem since it's only point is to help facilitate access control for font assets.  The last version was released 2 years ago.

**Comment by jjb** [comment]
Looks like there was a release done since this card was made, :tada: 🕺
