### ISSUE TITLE
Not working on Heroku/Cloudfront

### ISSUE THREAD

**Issue by cmalpeli** [ericallam/font_assets#42]
Any suggestions for debugging?

I'm not seeing the headers come through on Heroku via Cloudfront.  Here is the origin URL:

curl -I  http://jobboardio.herokuapp.com/assets/fontawesome-webfont-f55867ea3d66b55c6748925a4d91ff28.woff2?v=4.4.0
HTTP/1.1 200 OK
Server: Cowboy
Date: Tue, 18 Aug 2015 01:30:52 GMT
Connection: keep-alive
Last-Modified: Tue, 18 Aug 2015 01:25:22 GMT
Content-Type: application/font-woff2
Cache-Control: public, max-age=31557600
Vary: Accept-Encoding
Content-Length: 64464
Via: 1.1 vegur

I have `config.font_assets.origin = '*'` set in my `production.rb`

**Comment by mepster** [comment]
Support for woff2 is fixed in master, but not in the latest release 0.1.11. In the meantime you can do this:
gem 'font_assets', github: 'ericallam/font_assets', ref: '457dcfddc4318e83679e9a0935612924b7717085'

**Comment by ericallam** [comment]
I just created a new release `0.1.12` that includes the woff2 fix in master.
