### ISSUE TITLE
Not working for woff2 format

### ISSUE THREAD

**Issue by cmalpeli** [ericallam/font_assets#43]
I am not seeing headers come through for woff2 format.  woff works fine.

curl -I  http://jobboardio.herokuapp.com/assets/fontawesome-webfont-f55867ea3d66b55c6748925a4d91ff28.woff2?v=4.4.0
HTTP/1.1 200 OK
Server: Cowboy
Date: Tue, 18 Aug 2015 01:30:52 GMT
Connection: keep-alive
Last-Modified: Tue, 18 Aug 2015 01:25:22 GMT
Content-Type: application/font-woff2
Cache-Control: public, max-age=31557600
Vary: Accept-Encoding
Content-Length: 64464
Via: 1.1 vegur

url -I http://jobboardio.herokuapp.com/assets/fontawesome-webfont-ff568d080db0ded7af908b4ab985a045.woff
HTTP/1.1 200 OK
Server: Cowboy
Date: Tue, 18 Aug 2015 01:43:55 GMT
Connection: keep-alive
Last-Modified: Tue, 18 Aug 2015 01:39:06 GMT
Content-Type: application/font-woff
Cache-Control: public, max-age=31557600
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET
Access-Control-Allow-Headers: x-requested-with
Access-Control-Max-Age: 3628800
Vary: Accept-Encoding
Content-Length: 81284
Via: 1.1 vegur

**Comment by michaelwalters** [comment]
Why did you close this issue?  I'm seeing the same thing with cloudfront and font_assets.

**Comment by cmalpeli** [comment]
Unintentional - sorry about that!

**Comment by cmalpeli** [comment]
Err - sorry, yes it was intentional - there is already an issue for this: https://github.com/ericallam/font_assets/issues/37

**Comment by michaelwalters** [comment]
Thanks for linking them...makes sense now.
