### ISSUE TITLE
Is the gem thread safe?

### ISSUE THREAD

**Issue by PericlesTheo** [ericallam/font_assets#47]
Hey humans,

I see there are 2 open pull requests that propose making the gem thread safe. Any news on that front?

Cheers!

https://github.com/ericallam/font_assets/pull/26
https://github.com/ericallam/font_assets/pull/27

**Comment by ericallam** [comment]
@PericlesTheo I've just merged #27 and all the tests are passing, but I'd like to get confirmation that this doesn't break anything before I release a new version of the gem. Could you test it out master for me and make it it's working? After that I will release `0.1.13`
