### ISSUE TITLE
"No such middleware to insert before: ActionDispatch::Static" on Rails 5.0.2

### ISSUE THREAD

**Issue by christiannelson** [ericallam/font_assets#55]
Something font_assets is depending on in the middleware chain has changed in Rails 5.0.x.

**Comment by sevenseacat** [comment]
Same error here. It looks like that means you've got `config.serve_static_assets = false`, which according to https://github.com/ericallam/font_assets#important means this gem isn't for you. (Or me.)

**Comment by christiannelson** [comment]
Ah, that makes sense. I saw the error when I ran in production mode locally, which was missing the env var flag for enabling static assets serving. All good.
